### ISSUE TITLE
[ECOSYSTEM CHALLENGE] Using Remix And MetaMask On Moonbeam

### ISSUE THREAD

**Issue by albertov19** [dotrungkien/moonbeam-hands-on#1]
Hi dotrungkien,

Thanks for participating in the challenge. There is an issue with your submission, it seems that the allowance (approve for an external spender) was not correctly set.

Please verify this and let me know so I can check this again.

Regards
Alberto

**Comment by dotrungkien** [comment]
hi @albertov19 , i missed the approve transaction, just updated 👍 
Please check it again.
Thank you.
